In [1]:
import numpy as np

In [5]:
"""
Write a Python function that computes the dot product of a matrix and a vector. The function should return a list representing the resulting vector if the operation is valid, or -1 if the matrix and vector dimensions are incompatible. A matrix (a list of lists) can be dotted with a vector (a list) only if the number of columns in the matrix equals the length of the vector. For example, an n x m matrix requires a vector of length m.
"""

def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.
    arr1 = np.array(a)
    arr2 = np.array(b)

    if arr1.shape[1] != arr2.shape[0]:
        return -1
    
    else: 
        return np.dot(arr1, arr2)


print(matrix_dot_vector([[1, 2], [3, 4]], [5, 6]))

[17 39]


In [7]:
"""
Write a Python function that transposes a matrix. The function should return a new matrix that is the transpose of the input matrix. For example, if the input matrix is:

[
[1, 2, 3],
[4, 5, 6]
]

The function should return:

[
[1, 4],
[2, 5],
[3, 6]
"""

def transpose_matrix(a: list[list[int|float]]):

    arr = np.array(a)
    return np.transpose(arr)

print(transpose_matrix([[1, 2, 3], [4, 5, 6]]))

[[1 4]
 [2 5]
 [3 6]]


In [10]:
"""
Write a Python function that reshapes a given matrix into a specified shape. if it cant be reshaped return back an empty list [ ]
"""
def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]):

    arr = np.array(a)

    try:
        return np.reshape(arr, new_shape)
    except:
        return []
    

print(reshape_matrix([[1, 2, 3], [4, 5, 6]], (2, 3)))

[[1 2 3]
 [4 5 6]]


In [18]:
"""
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.
"""

def calculate_matrix_mean(matrix: list[list[float]], mode: str):

    arr = np.array(matrix)

    if mode == "row":
        means = np.mean(arr, axis = 1)
    
    elif mode == "column":
        means = np.mean(arr, axis = 0)
    
    return means

print(calculate_matrix_mean([[1, 2, 3], [4, 5, 6], [7, 8, 9]], "row"))

[2. 5. 8.]


In [22]:
"""
Write a Python function that multiplies a matrix by a scalar and returns the result.
"""

def scalar_multiply(matrix: list[list[int|float]], scalar: int|float):

    arr = np.array(matrix)

    return arr*scalar

print(scalar_multiply([[1, 2], [3, 4]], 2))

[[2 4]
 [6 8]]


In [7]:
"""
Write a Python function that calculates the eigenvalues of a 2x2 matrix. The function should return a list containing the eigenvalues, sort values from highest to lowest.
"""


def calculate_eigenvalues(matrix: list[list[float|int]]):
    arr = np.array(matrix)
    eigenvalues, eigenvectors = np.linalg.eig(arr)
    return sorted(eigenvalues, reverse=True)

print(calculate_eigenvalues([[2, 1], [1, 2]]))


[np.float64(3.0), np.float64(1.0)]


In [13]:
"""
Write a Python function that transforms a given matrix A using the operation T⁻¹AS, where T and S are invertible matrices. The function should first validate if the matrices T and S are invertible, and then perform the transformation. In cases where there is no solution return -1
"""
def transform_matrix(A: list[list[int|float]], T: list[list[int|float]], S: list[list[int|float]]):

    arr1 = np.array(A)
    arr2 = np.array(T)
    arr3 = np.array(S)

    try:
        arr2_inv = np.linalg.inv(arr2)
        arr3_inv = np.linalg.inv(arr3)
        return arr2_inv @ arr1 @ arr3 # @ is the matrix multiplication operator in numpy
    
    except:
        return -1

print(transform_matrix([[1, 2], [3, 4]], [[1, 0], [0, 1]], [[1, 0], [0, 1]]))

[[1. 2.]
 [3. 4.]]


In [17]:
"""
Write a Python function to calculate the covariance matrix for a given set of vectors. The function should take a list of lists, where each inner list represents a feature with its observations, and return a covariance matrix as a list of lists. Additionally, provide test cases to verify the correctness of your implementation.
"""
def calculate_covariance_matrix(vectors: list[list[float]]):

    arr = np.array(vectors)
    return np.cov(arr)

print(calculate_covariance_matrix([[1, 2], [3, 4], [5, 6]]))

[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [25]:
"""
Write a Python function that uses the Jacobi method to solve a system of linear equations given by Ax = b. The function should iterate n times, rounding each intermediate solution to four decimal places, and return the approximate solution x.
"""

def solve_jacobi(A: np.ndarray, b: np.ndarray, n: int):

    x = np.array([0,0,0])

    D = np.diag(A) # this will just provide the diagonal elements
    R = A - np.diag(D) # this will give the complete diagonal matrix in the correct shape

    for i in range(n):
        x = (b - np.dot(R, x))/D
        x = np.round(x, 4)
    
    return x

A = np.array([[5, -2, 3], [-3, 9, 1], [2, -1, -7]])
b = np.array([-1, 2, 3])
n = 2

print(solve_jacobi(A, b, n))

[ 0.146   0.2032 -0.5175]


In [ ]:
"""
Write a Python function that approximates the Singular Value Decomposition on a 2x2 matrix by using the jacobian method and without using numpy svd function. Return U, Σ, and V matrices.
"""
def svd_2x2(A: np.ndarray) -> tuple:
    # Initialize U and V as identity matrices
    U = np.eye(2)
    V = np.eye(2)
    
    # Work with B = A initially
    B = A.copy()
    
    # Compute C = B^T B
    C = B.T @ B
    
    # Get off-diagonal elements
    off_diag = C - np.diag(np.diag(C))
    
    # While significant off-diagonal elements exist
    while np.max(np.abs(off_diag)) > 1e-10:
        # Find largest off-diagonal element
        print("this is the off_diag", off_diag)
        p, q = np.unravel_index(np.argmax(np.abs(off_diag)), off_diag.shape)
        
        # Compute rotation angle
        # arctan2 is used here because:
        # 1. It handles the full range of angles (-π to π) unlike regular arctan (-π/2 to π/2)
        # 2. It correctly handles the signs of numerator and denominator to determine quadrant
        # 3. For SVD, we need the angle that diagonalizes the matrix, which is given by:
        #    θ = 1/2 * arctan2(2*c_pq, c_pp - c_qq) where c_ij are elements of C = A^T A
        theta = 0.5 * np.arctan2(2 * C[p,q], C[p,p] - C[q,q])
        
        # Construct Givens rotation matrix
        G = np.array([[np.cos(theta), -np.sin(theta)],
                     [np.sin(theta), np.cos(theta)]])
        
        # Update matrices
        B = B @ G.T
        V = V @ G.T
        
        # Recompute C and off-diagonal elements
        C = B.T @ B
        off_diag = C - np.diag(np.diag(C))
    
    # Compute singular values
    singular_values = np.sqrt(np.diag(C))
    Sigma = np.diag(singular_values)
    
    # Compute U using B and Sigma
    U = B @ np.linalg.inv(Sigma)
    
    return U, Sigma, V

# Test the function
A = np.array([[1, 2], 
              [3, 4]])
U, Sigma, V = svd_2x2(A)

print("Original matrix A:")
print(A)
print("\nU matrix:")
print(U)
print("\nSigma matrix:")
print(Sigma)
print("\nV matrix:")
print(V)
print("\nVerification - reconstructed A:")
print(U @ Sigma @ V.T)


In [49]:
"""
Write a Python function that calculates the determinant of a 4x4 matrix using Laplace's Expansion method. The function should take a single argument, a 4x4 matrix represented as a list of lists, and return the determinant of the matrix. The elements of the matrix can be integers or floating-point numbers. Implement the function recursively to handle the computation of determinants for the 3x3 minor matrices.
"""
def determinant_4x4(matrix) -> float:
    arr = np.array(matrix)
    
    # For Laplace expansion, we only need to iterate along one row/column
    # Let's use first row (i=0)
    det_arr = 0
    for j in range(arr.shape[1]):
        # Get minor matrix by removing first row and column j
        minor = np.delete(np.delete(arr, 0, axis=0), j, axis=1)
        # Calculate cofactor
        cofactor = (-1)**(0+j) * calculate_3x3_determinant(minor)
        # Add to determinant
        det_arr += arr[0,j] * cofactor
    
    return int(det_arr)

def calculate_3x3_determinant(arr):
    arr = np.array(arr)
    return np.linalg.det(arr)


a = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a = np.array(a)

print(determinant_4x4(a))
print(determinant_4x4([[4, 3, 2, 1], [3, 2, 1, 4], [2, 1, 4, 3], [1, 4, 3, 2]]))

0
-160
