In [4]:
import numpy as np

In [5]:
"""
Write a Python function that computes the dot product of a matrix and a vector. The function should return a list representing the resulting vector if the operation is valid, or -1 if the matrix and vector dimensions are incompatible. A matrix (a list of lists) can be dotted with a vector (a list) only if the number of columns in the matrix equals the length of the vector. For example, an n x m matrix requires a vector of length m.
"""

def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.
    arr1 = np.array(a)
    arr2 = np.array(b)

    if arr1.shape[1] != arr2.shape[0]:
        return -1
    
    else: 
        return np.dot(arr1, arr2)


print(matrix_dot_vector([[1, 2], [3, 4]], [5, 6]))

[17 39]


In [7]:
"""
Write a Python function that transposes a matrix. The function should return a new matrix that is the transpose of the input matrix. For example, if the input matrix is:

[
[1, 2, 3],
[4, 5, 6]
]

The function should return:

[
[1, 4],
[2, 5],
[3, 6]
"""

def transpose_matrix(a: list[list[int|float]]):

    arr = np.array(a)
    return np.transpose(arr)

print(transpose_matrix([[1, 2, 3], [4, 5, 6]]))

[[1 4]
 [2 5]
 [3 6]]


In [10]:
"""
Write a Python function that reshapes a given matrix into a specified shape. if it cant be reshaped return back an empty list [ ]
"""
def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]):

    arr = np.array(a)

    try:
        return np.reshape(arr, new_shape)
    except:
        return []
    

print(reshape_matrix([[1, 2, 3], [4, 5, 6]], (2, 3)))

[[1 2 3]
 [4 5 6]]


In [18]:
"""
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.
"""

def calculate_matrix_mean(matrix: list[list[float]], mode: str):

    arr = np.array(matrix)

    if mode == "row":
        means = np.mean(arr, axis = 1)
    
    elif mode == "column":
        means = np.mean(arr, axis = 0)
    
    return means

print(calculate_matrix_mean([[1, 2, 3], [4, 5, 6], [7, 8, 9]], "row"))

[2. 5. 8.]


In [22]:
"""
Write a Python function that multiplies a matrix by a scalar and returns the result.
"""

def scalar_multiply(matrix: list[list[int|float]], scalar: int|float):

    arr = np.array(matrix)

    return arr*scalar

print(scalar_multiply([[1, 2], [3, 4]], 2))

[[2 4]
 [6 8]]
